### ISSUE TITLE
React integration

### ISSUE THREAD

**Issue by bouiboui** [extend-chrome/typescript-chrome-extension-starter#1]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

Hi! 

You say that the extension is React-ready, it would be nice to have some guidance for doing so. 
I've tried to add babel compilation to the rollup config file, but things got confusing very quickly.

### Your Proposal for Changes

Do you have any documentation or an example of a React project using your library?

Thanks!

**Comment by jacksteamdev** [comment]
The JSX compilation is done through the TypeScript compiler. Name your React files with the `tsx` extension and you're done! :100: 

```typescript
// App.tsx <- tsx for files with jsx in them

import React from 'react'

export const App = () => (
  <div>App</div>
)
```

```typescript
// index.tsx

import React from 'react'
import { render } from 'react-dom'

import { App } from './app'

render(<App/>, document.getElementById('root'))
```

@bouiboui You're right, we should an example of usage with React. I'll probably do this in a separate boilerplate, but if you want to make a PR to this repo, that would be awesome!

btw, I personally try to stay away from babel and webpack, for the reasons you mentioned (things get confusing :confused:).

**Comment by bouiboui** [comment]
Great! I forgot to include the `.tsx` file in a `<script/>` tag in the html file I wanted to build with React, ex:
```html
<!DOCTYPE html>
<html lang="en">
<head>...</head>
<body>
...
<script src="popup.tsx"></script>
</body>
</html>
```

That's awesome, I will do a PR to update the documentation when I find the time 😄 
Thanks a lot for this project, it's perfect.
